import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';

import '../../database/drift/local_database.dart';
import '../../database/drift/notes/notes_dao.dart';

class ImportNotesPage extends ConsumerStatefulWidget {
  const ImportNotesPage({super.key});

  @override
  ConsumerState<ImportNotesPage> createState() => _ImportNotesPageState();
}

class _ImportNotesPageState extends ConsumerState<ImportNotesPage> {
  PlatformFile? _selectedFile;
  bool _isImporting = false;
  String? _statusMessage;
  bool _isError = false;

  Future<void> _pickFile() async {
    try {

      PlatformFile? file = await FilePicker.pickFile(
        type: FileType.custom,
        allowedExtensions: ['json', 'csv'],
      );

      if (file != null) {
        setState(() {
          _selectedFile = file;
          _statusMessage = null; // Clear previous messages
          _isError = false;
        });
      }
    } catch (e) {
      setState(() {
        _isError = true;
        _statusMessage = 'Failed to pick file: $e';
      });
    }
  }

  Future<void> _processImport() async {
    if (_selectedFile == null) return;

    setState(() {
      _isImporting = true;
      _statusMessage = 'Reading file...';
      _isError = false;
    });

    try {
      // syntax for reading bytes cross-platform (works on Windows & Android)
      final bytes = await _selectedFile!.readAsBytes();
      final fileString = utf8.decode(bytes);

      final notesDao = ref.read(notesDaoProvider);
      List<dynamic> rawData = [];

      if (_selectedFile!.extension == 'json') {
        rawData = jsonDecode(fileString) as List<dynamic>;
      } else if (_selectedFile!.extension == 'csv') {
        // Simple CSV parser for fallback (JSON is highly recommended for exact data types)
        rawData = _parseCsvToJson(fileString);
      }

      if (rawData.isEmpty) {
        throw Exception("The file is empty or formatted incorrectly.");
      }

      setState(() {
        _statusMessage = 'Restoring ${rawData.length} notes...';
      });

      // Convert Maps back to Drift Note objects
      // Note.fromJson is automatically generated by Drift!
      List<Note> parsedNotes = [];
      for (var map in rawData) {
        try {
          parsedNotes.add(Note.fromJson(map as Map<String, dynamic>));
        } catch (e) {
          debugPrint("Failed to parse a note: $e");
          // Skip invalid rows silently
        }
      }

      // Insert/Update into database
      await notesDao.importNotes(parsedNotes);

      setState(() {
        _isImporting = false;
        _statusMessage = 'Successfully imported ${parsedNotes.length} notes!';
        _isError = false;
      });

    } catch (e) {
      setState(() {
        _isImporting = false;
        _isError = true;
        _statusMessage = 'Import failed: $e\nMake sure this is a valid NoteIt export file.';
      });
    }
  }

  /// A basic CSV parser that handles the format we generated in the Export page.
  List<Map<String, dynamic>> _parseCsvToJson(String csvString) {
    if (csvString.trim().isEmpty) return [];

    final lines = csvString.split('\n').where((line) => line.trim().isNotEmpty).toList();
    if (lines.length < 2) return []; // Needs at least headers and one data row

    final headers = lines.first.split(',');
    List<Map<String, dynamic>> results = [];

    for (int i = 1; i < lines.length; i++) {
      // Basic regex to split by commas but ignore commas inside quotes
      final RegExp csvSplitter = RegExp(r',(?=(?:[^"]*"[^"]*")*[^"]*$)');
      final values = lines[i].split(csvSplitter);

      Map<String, dynamic> rowMap = {};
      for (int j = 0; j < headers.length; j++) {
        if (j < values.length) {
          String val = values[j].trim();
          // Remove surrounding quotes and un-escape double quotes
          if (val.startsWith('"') && val.endsWith('"')) {
            val = val.substring(1, val.length - 1).replaceAll('""', '"');
          }

          // Attempt basic type conversion to satisfy Drift's Note.fromJson
          if (val == 'true') {rowMap[headers[j]] = true;}
          else if (val == 'false') {rowMap[headers[j]] = false;}
          else if (int.tryParse(val) != null) {rowMap[headers[j]] = int.parse(val);}
          else {rowMap[headers[j]] = val;}
        }
      }
      results.add(rowMap);
    }
    return results;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Import Notes'),
        centerTitle: true,
      ),
      body: Center(
        // Responsive constraint matching the Export Page
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 700),
          child: ListView(
            padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 24.0),
            children: [
              const Text(
                'Restore your Backup',
                style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16),
              const Text(
                'Select a previously exported .json or .csv file to restore your notes. '
                    'If a note already exists, it will be updated. JSON format is highly recommended for perfect restoration.',
                style: TextStyle(fontSize: 14, color: Colors.grey),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 32),

              // STEP 1: PICK FILE
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(24.0),
                  child: Column(
                    children: [
                      const Icon(Icons.upload_file, size: 48, color: Colors.grey),
                      const SizedBox(height: 16),
                      Text(
                        _selectedFile != null
                            ? 'Selected: ${_selectedFile!.name}'
                            : 'No file selected',
                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                        textAlign: TextAlign.center,
                      ),
                      const SizedBox(height: 24),
                      OutlinedButton.icon(
                        onPressed: _isImporting ? null : _pickFile,
                        icon: const Icon(Icons.folder_open),
                        label: const Text('Choose File'),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),

              // STATUS MESSAGE
              if (_statusMessage != null)
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: _isError
                        ? Colors.red.withValues(alpha: 0.1)
                        : Colors.green.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: _isError ? Colors.red : Colors.green,
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        _isError ? Icons.error_outline : Icons.check_circle_outline,
                        color: _isError ? Colors.red : Colors.green,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          _statusMessage!,
                          style: TextStyle(
                            color: _isError ? Colors.red.shade700 : Colors.green.shade700,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

              const SizedBox(height: 32),

              // STEP 2: IMPORT BUTTON
              SizedBox(
                height: 54,
                child: FilledButton.icon(
                  onPressed: (_selectedFile == null || _isImporting) ? null : _processImport,
                  icon: _isImporting
                      ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)
                  )
                      : const Icon(Icons.restore),
                  label: Text(
                    _isImporting ? 'Processing...' : 'Restore Notes',
                    style: const TextStyle(fontSize: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}